<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */
$isHidePrice = $block->getItem()->getProduct()->getIsHidePrice();
?>
<?php if (!$isHidePrice) :?>
    <?php foreach ($block->getChildNames() as $childName) : ?>
        <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
    <?php endforeach;?>
<?php endif; ?>
